//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDemo.hh {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="hh.ELDWebServiceSoap")]
    public interface ELDWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPath", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPath(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPath", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPathAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FenPingII", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FenPingII(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.ELDRegion[] arrEldRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FenPingII", ReplyAction="*")]
        System.Threading.Tasks.Task<string> FenPingIIAsync(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.ELDRegion[] arrEldRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddGaoJingXinXiToDb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddGaoJingXinXiToDb(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.DisplayObj displayObj, int RegionIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddGaoJingXinXiToDb", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddGaoJingXinXiToDbAsync(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.DisplayObj displayObj, int RegionIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendObjToELD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendObjToELD(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.DisplayObj displayObj, int RegionIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendObjToELD", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendObjToELDAsync(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.DisplayObj displayObj, int RegionIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendArrToELD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendArrToELD(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.ELDRegion region, ClientDemo.hh.DisplayObj[] arrdisplayObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendArrToELD", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendArrToELDAsync(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.ELDRegion region, ClientDemo.hh.DisplayObj[] arrdisplayObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendToELD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendToELD(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.ELDRegion region, ClientDemo.hh.DisplayObj displayObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendToELD", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendToELDAsync(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.ELDRegion region, ClientDemo.hh.DisplayObj displayObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdjustTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AdjustTime(ClientDemo.hh.MyTDeviceParam myTDeviceParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdjustTime", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AdjustTimeAsync(ClientDemo.hh.MyTDeviceParam myTDeviceParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetSwitch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SetSwitch(int val);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetSwitch", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SetSwitchAsync(int val);
        
        // CODEGEN: 参数“fileBytes”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientDemo.hh.UploadFileResponse UploadFile(ClientDemo.hh.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientDemo.hh.UploadFileResponse> UploadFileAsync(ClientDemo.hh.UploadFileRequest request);
        
        // CODEGEN: 参数“fileBytes”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFileII", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientDemo.hh.UploadFileIIResponse UploadFileII(ClientDemo.hh.UploadFileIIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFileII", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientDemo.hh.UploadFileIIResponse> UploadFileIIAsync(ClientDemo.hh.UploadFileIIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendWords(string words);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWords", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendWordsAsync(string words);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTextObj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientDemo.hh.TextObj GetTextObj(string eldIp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTextObj", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientDemo.hh.TextObj> GetTextObjAsync(string eldIp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRoadsByDisplayType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientDemo.hh.road[] GetRoadsByDisplayType(int displayType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRoadsByDisplayType", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientDemo.hh.road[]> GetRoadsByDisplayTypeAsync(int displayType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientDemo.hh.region[] Search(string eldIp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientDemo.hh.region[]> SearchAsync(string eldIp);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MyTDeviceParam : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int devTypeField;
        
        private int locPortField;
        
        private string rmtHostField;
        
        private int rmtPortField;
        
        private int dstAddrField;
        
        private int displayTypeField;
        
        private int r_idField;
        
        private string r_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int devType {
            get {
                return this.devTypeField;
            }
            set {
                this.devTypeField = value;
                this.RaisePropertyChanged("devType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int locPort {
            get {
                return this.locPortField;
            }
            set {
                this.locPortField = value;
                this.RaisePropertyChanged("locPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string rmtHost {
            get {
                return this.rmtHostField;
            }
            set {
                this.rmtHostField = value;
                this.RaisePropertyChanged("rmtHost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int rmtPort {
            get {
                return this.rmtPortField;
            }
            set {
                this.rmtPortField = value;
                this.RaisePropertyChanged("rmtPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int dstAddr {
            get {
                return this.dstAddrField;
            }
            set {
                this.dstAddrField = value;
                this.RaisePropertyChanged("dstAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int displayType {
            get {
                return this.displayTypeField;
            }
            set {
                this.displayTypeField = value;
                this.RaisePropertyChanged("displayType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int r_id {
            get {
                return this.r_idField;
            }
            set {
                this.r_idField = value;
                this.RaisePropertyChanged("r_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string r_name {
            get {
                return this.r_nameField;
            }
            set {
                this.r_nameField = value;
                this.RaisePropertyChanged("r_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class region : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int seqField;
        
        private int region_IndexField;
        
        private int road_idField;
        
        private int leftField;
        
        private int topField;
        
        private int widthField;
        
        private int heightField;
        
        private int borderField;
        
        private int region_TypeField;
        
        private string eLD_IPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int seq {
            get {
                return this.seqField;
            }
            set {
                this.seqField = value;
                this.RaisePropertyChanged("seq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Region_Index {
            get {
                return this.region_IndexField;
            }
            set {
                this.region_IndexField = value;
                this.RaisePropertyChanged("Region_Index");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int road_id {
            get {
                return this.road_idField;
            }
            set {
                this.road_idField = value;
                this.RaisePropertyChanged("road_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
                this.RaisePropertyChanged("left");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
                this.RaisePropertyChanged("top");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
                this.RaisePropertyChanged("border");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Region_Type {
            get {
                return this.region_TypeField;
            }
            set {
                this.region_TypeField = value;
                this.RaisePropertyChanged("Region_Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ELD_IP {
            get {
                return this.eLD_IPField;
            }
            set {
                this.eLD_IPField = value;
                this.RaisePropertyChanged("ELD_IP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class road : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int r_idField;
        
        private string r_nameField;
        
        private string picPathField;
        
        private bool isCreatePictureField;
        
        private decimal r_widthField;
        
        private int eld_pictureWidthField;
        
        private int eld_pictureHeightField;
        
        private int eld_regionWidthField;
        
        private int eld_regionHeightField;
        
        private string eld_rmtHostField;
        
        private bool isConnectELDField;
        
        private int locPortField;
        
        private int rmtPortField;
        
        private string remarkField;
        
        private int displayTypeField;
        
        private string areaField;
        
        private bool isDownloadPictureField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int r_id {
            get {
                return this.r_idField;
            }
            set {
                this.r_idField = value;
                this.RaisePropertyChanged("r_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string r_name {
            get {
                return this.r_nameField;
            }
            set {
                this.r_nameField = value;
                this.RaisePropertyChanged("r_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string picPath {
            get {
                return this.picPathField;
            }
            set {
                this.picPathField = value;
                this.RaisePropertyChanged("picPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsCreatePicture {
            get {
                return this.isCreatePictureField;
            }
            set {
                this.isCreatePictureField = value;
                this.RaisePropertyChanged("IsCreatePicture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal r_width {
            get {
                return this.r_widthField;
            }
            set {
                this.r_widthField = value;
                this.RaisePropertyChanged("r_width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int eld_pictureWidth {
            get {
                return this.eld_pictureWidthField;
            }
            set {
                this.eld_pictureWidthField = value;
                this.RaisePropertyChanged("eld_pictureWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int eld_pictureHeight {
            get {
                return this.eld_pictureHeightField;
            }
            set {
                this.eld_pictureHeightField = value;
                this.RaisePropertyChanged("eld_pictureHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int eld_regionWidth {
            get {
                return this.eld_regionWidthField;
            }
            set {
                this.eld_regionWidthField = value;
                this.RaisePropertyChanged("eld_regionWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int eld_regionHeight {
            get {
                return this.eld_regionHeightField;
            }
            set {
                this.eld_regionHeightField = value;
                this.RaisePropertyChanged("eld_regionHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string eld_rmtHost {
            get {
                return this.eld_rmtHostField;
            }
            set {
                this.eld_rmtHostField = value;
                this.RaisePropertyChanged("eld_rmtHost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool IsConnectELD {
            get {
                return this.isConnectELDField;
            }
            set {
                this.isConnectELDField = value;
                this.RaisePropertyChanged("IsConnectELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int locPort {
            get {
                return this.locPortField;
            }
            set {
                this.locPortField = value;
                this.RaisePropertyChanged("locPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int rmtPort {
            get {
                return this.rmtPortField;
            }
            set {
                this.rmtPortField = value;
                this.RaisePropertyChanged("rmtPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int displayType {
            get {
                return this.displayTypeField;
            }
            set {
                this.displayTypeField = value;
                this.RaisePropertyChanged("displayType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool IsDownloadPicture {
            get {
                return this.isDownloadPictureField;
            }
            set {
                this.isDownloadPictureField = value;
                this.RaisePropertyChanged("IsDownloadPicture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TextObj : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int text_IdField;
        
        private int region_IndexField;
        
        private int leftField;
        
        private int topField;
        
        private int alignmentField;
        
        private int widthField;
        
        private int heightField;
        
        private int transparentField;
        
        private int borderField;
        
        private string strField;
        
        private string fontnameField;
        
        private int fontsizeField;
        
        private int fontcolorField;
        
        private int fontstyleField;
        
        private int wordwrapField;
        
        private int inmethodField;
        
        private int inspeedField;
        
        private int outmethodField;
        
        private int outspeedField;
        
        private int stopmethodField;
        
        private int stopspeedField;
        
        private int stoptimeField;
        
        private string eLD_IPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Text_Id {
            get {
                return this.text_IdField;
            }
            set {
                this.text_IdField = value;
                this.RaisePropertyChanged("Text_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Region_Index {
            get {
                return this.region_IndexField;
            }
            set {
                this.region_IndexField = value;
                this.RaisePropertyChanged("Region_Index");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
                this.RaisePropertyChanged("left");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
                this.RaisePropertyChanged("top");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int alignment {
            get {
                return this.alignmentField;
            }
            set {
                this.alignmentField = value;
                this.RaisePropertyChanged("alignment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int transparent {
            get {
                return this.transparentField;
            }
            set {
                this.transparentField = value;
                this.RaisePropertyChanged("transparent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
                this.RaisePropertyChanged("border");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string str {
            get {
                return this.strField;
            }
            set {
                this.strField = value;
                this.RaisePropertyChanged("str");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string fontname {
            get {
                return this.fontnameField;
            }
            set {
                this.fontnameField = value;
                this.RaisePropertyChanged("fontname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int fontsize {
            get {
                return this.fontsizeField;
            }
            set {
                this.fontsizeField = value;
                this.RaisePropertyChanged("fontsize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int fontcolor {
            get {
                return this.fontcolorField;
            }
            set {
                this.fontcolorField = value;
                this.RaisePropertyChanged("fontcolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int fontstyle {
            get {
                return this.fontstyleField;
            }
            set {
                this.fontstyleField = value;
                this.RaisePropertyChanged("fontstyle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int wordwrap {
            get {
                return this.wordwrapField;
            }
            set {
                this.wordwrapField = value;
                this.RaisePropertyChanged("wordwrap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int inmethod {
            get {
                return this.inmethodField;
            }
            set {
                this.inmethodField = value;
                this.RaisePropertyChanged("inmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int inspeed {
            get {
                return this.inspeedField;
            }
            set {
                this.inspeedField = value;
                this.RaisePropertyChanged("inspeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int outmethod {
            get {
                return this.outmethodField;
            }
            set {
                this.outmethodField = value;
                this.RaisePropertyChanged("outmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int outspeed {
            get {
                return this.outspeedField;
            }
            set {
                this.outspeedField = value;
                this.RaisePropertyChanged("outspeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int stopmethod {
            get {
                return this.stopmethodField;
            }
            set {
                this.stopmethodField = value;
                this.RaisePropertyChanged("stopmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int stopspeed {
            get {
                return this.stopspeedField;
            }
            set {
                this.stopspeedField = value;
                this.RaisePropertyChanged("stopspeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int stoptime {
            get {
                return this.stoptimeField;
            }
            set {
                this.stoptimeField = value;
                this.RaisePropertyChanged("stoptime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ELD_IP {
            get {
                return this.eLD_IPField;
            }
            set {
                this.eLD_IPField = value;
                this.RaisePropertyChanged("ELD_IP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClockPro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int leftField;
        
        private int topField;
        
        private int widthField;
        
        private int heightField;
        
        private int transparentField;
        
        private int borderField;
        
        private int offsetField;
        
        private ushort bkcolorField;
        
        private ushort bordercolorField;
        
        private ushort borderwidthField;
        
        private int bordershapeField;
        
        private int dotradiusField;
        
        private int adotwidthField;
        
        private ushort adotcolorField;
        
        private int bdotwidthField;
        
        private ushort bdotcolorField;
        
        private int hourwidthField;
        
        private ushort hourcolorField;
        
        private int minutewidthField;
        
        private ushort minutecolorField;
        
        private int secondwidthField;
        
        private ushort secondcolorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
                this.RaisePropertyChanged("left");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
                this.RaisePropertyChanged("top");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int transparent {
            get {
                return this.transparentField;
            }
            set {
                this.transparentField = value;
                this.RaisePropertyChanged("transparent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
                this.RaisePropertyChanged("border");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ushort bkcolor {
            get {
                return this.bkcolorField;
            }
            set {
                this.bkcolorField = value;
                this.RaisePropertyChanged("bkcolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public ushort bordercolor {
            get {
                return this.bordercolorField;
            }
            set {
                this.bordercolorField = value;
                this.RaisePropertyChanged("bordercolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public ushort borderwidth {
            get {
                return this.borderwidthField;
            }
            set {
                this.borderwidthField = value;
                this.RaisePropertyChanged("borderwidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int bordershape {
            get {
                return this.bordershapeField;
            }
            set {
                this.bordershapeField = value;
                this.RaisePropertyChanged("bordershape");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int dotradius {
            get {
                return this.dotradiusField;
            }
            set {
                this.dotradiusField = value;
                this.RaisePropertyChanged("dotradius");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int adotwidth {
            get {
                return this.adotwidthField;
            }
            set {
                this.adotwidthField = value;
                this.RaisePropertyChanged("adotwidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public ushort adotcolor {
            get {
                return this.adotcolorField;
            }
            set {
                this.adotcolorField = value;
                this.RaisePropertyChanged("adotcolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int bdotwidth {
            get {
                return this.bdotwidthField;
            }
            set {
                this.bdotwidthField = value;
                this.RaisePropertyChanged("bdotwidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public ushort bdotcolor {
            get {
                return this.bdotcolorField;
            }
            set {
                this.bdotcolorField = value;
                this.RaisePropertyChanged("bdotcolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int hourwidth {
            get {
                return this.hourwidthField;
            }
            set {
                this.hourwidthField = value;
                this.RaisePropertyChanged("hourwidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public ushort hourcolor {
            get {
                return this.hourcolorField;
            }
            set {
                this.hourcolorField = value;
                this.RaisePropertyChanged("hourcolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int minutewidth {
            get {
                return this.minutewidthField;
            }
            set {
                this.minutewidthField = value;
                this.RaisePropertyChanged("minutewidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public ushort minutecolor {
            get {
                return this.minutecolorField;
            }
            set {
                this.minutecolorField = value;
                this.RaisePropertyChanged("minutecolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int secondwidth {
            get {
                return this.secondwidthField;
            }
            set {
                this.secondwidthField = value;
                this.RaisePropertyChanged("secondwidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public ushort secondcolor {
            get {
                return this.secondcolorField;
            }
            set {
                this.secondcolorField = value;
                this.RaisePropertyChanged("secondcolor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DateTimePro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int alignmentField;
        
        private int leftField;
        
        private int topField;
        
        private int widthField;
        
        private int heightField;
        
        private int transparentField;
        
        private int borderField;
        
        private string fontnameField;
        
        private int fontsizeField;
        
        private int fontcolorField;
        
        private int fontstyleField;
        
        private int year_offsetField;
        
        private int month_offsetField;
        
        private int day_offsetField;
        
        private int sec_offsetField;
        
        private string formatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int alignment {
            get {
                return this.alignmentField;
            }
            set {
                this.alignmentField = value;
                this.RaisePropertyChanged("alignment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
                this.RaisePropertyChanged("left");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
                this.RaisePropertyChanged("top");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int transparent {
            get {
                return this.transparentField;
            }
            set {
                this.transparentField = value;
                this.RaisePropertyChanged("transparent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
                this.RaisePropertyChanged("border");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string fontname {
            get {
                return this.fontnameField;
            }
            set {
                this.fontnameField = value;
                this.RaisePropertyChanged("fontname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int fontsize {
            get {
                return this.fontsizeField;
            }
            set {
                this.fontsizeField = value;
                this.RaisePropertyChanged("fontsize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int fontcolor {
            get {
                return this.fontcolorField;
            }
            set {
                this.fontcolorField = value;
                this.RaisePropertyChanged("fontcolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int fontstyle {
            get {
                return this.fontstyleField;
            }
            set {
                this.fontstyleField = value;
                this.RaisePropertyChanged("fontstyle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int year_offset {
            get {
                return this.year_offsetField;
            }
            set {
                this.year_offsetField = value;
                this.RaisePropertyChanged("year_offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int month_offset {
            get {
                return this.month_offsetField;
            }
            set {
                this.month_offsetField = value;
                this.RaisePropertyChanged("month_offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int day_offset {
            get {
                return this.day_offsetField;
            }
            set {
                this.day_offsetField = value;
                this.RaisePropertyChanged("day_offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int sec_offset {
            get {
                return this.sec_offsetField;
            }
            set {
                this.sec_offsetField = value;
                this.RaisePropertyChanged("sec_offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("format");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PicturePro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int alignmentField;
        
        private int leftField;
        
        private int topField;
        
        private int widthField;
        
        private int heightField;
        
        private int transparentField;
        
        private int borderField;
        
        private string filenameField;
        
        private int inmethodField;
        
        private int inspeedField;
        
        private int outmethodField;
        
        private int outspeedField;
        
        private int stopmethodField;
        
        private int stopspeedField;
        
        private int stoptimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int alignment {
            get {
                return this.alignmentField;
            }
            set {
                this.alignmentField = value;
                this.RaisePropertyChanged("alignment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
                this.RaisePropertyChanged("left");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
                this.RaisePropertyChanged("top");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int transparent {
            get {
                return this.transparentField;
            }
            set {
                this.transparentField = value;
                this.RaisePropertyChanged("transparent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
                this.RaisePropertyChanged("border");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("filename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int inmethod {
            get {
                return this.inmethodField;
            }
            set {
                this.inmethodField = value;
                this.RaisePropertyChanged("inmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int inspeed {
            get {
                return this.inspeedField;
            }
            set {
                this.inspeedField = value;
                this.RaisePropertyChanged("inspeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int outmethod {
            get {
                return this.outmethodField;
            }
            set {
                this.outmethodField = value;
                this.RaisePropertyChanged("outmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int outspeed {
            get {
                return this.outspeedField;
            }
            set {
                this.outspeedField = value;
                this.RaisePropertyChanged("outspeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int stopmethod {
            get {
                return this.stopmethodField;
            }
            set {
                this.stopmethodField = value;
                this.RaisePropertyChanged("stopmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int stopspeed {
            get {
                return this.stopspeedField;
            }
            set {
                this.stopspeedField = value;
                this.RaisePropertyChanged("stopspeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int stoptime {
            get {
                return this.stoptimeField;
            }
            set {
                this.stoptimeField = value;
                this.RaisePropertyChanged("stoptime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TextPro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int leftField;
        
        private int topField;
        
        private int alignmentField;
        
        private int widthField;
        
        private int heightField;
        
        private int transparentField;
        
        private int borderField;
        
        private string strField;
        
        private string fontnameField;
        
        private int fontsizeField;
        
        private int fontcolorField;
        
        private int fontstyleField;
        
        private int wordwrapField;
        
        private int inmethodField;
        
        private int inspeedField;
        
        private int outmethodField;
        
        private int outspeedField;
        
        private int stopmethodField;
        
        private int stopspeedField;
        
        private int stoptimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
                this.RaisePropertyChanged("left");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
                this.RaisePropertyChanged("top");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int alignment {
            get {
                return this.alignmentField;
            }
            set {
                this.alignmentField = value;
                this.RaisePropertyChanged("alignment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int transparent {
            get {
                return this.transparentField;
            }
            set {
                this.transparentField = value;
                this.RaisePropertyChanged("transparent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
                this.RaisePropertyChanged("border");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string str {
            get {
                return this.strField;
            }
            set {
                this.strField = value;
                this.RaisePropertyChanged("str");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string fontname {
            get {
                return this.fontnameField;
            }
            set {
                this.fontnameField = value;
                this.RaisePropertyChanged("fontname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int fontsize {
            get {
                return this.fontsizeField;
            }
            set {
                this.fontsizeField = value;
                this.RaisePropertyChanged("fontsize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int fontcolor {
            get {
                return this.fontcolorField;
            }
            set {
                this.fontcolorField = value;
                this.RaisePropertyChanged("fontcolor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int fontstyle {
            get {
                return this.fontstyleField;
            }
            set {
                this.fontstyleField = value;
                this.RaisePropertyChanged("fontstyle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int wordwrap {
            get {
                return this.wordwrapField;
            }
            set {
                this.wordwrapField = value;
                this.RaisePropertyChanged("wordwrap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int inmethod {
            get {
                return this.inmethodField;
            }
            set {
                this.inmethodField = value;
                this.RaisePropertyChanged("inmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int inspeed {
            get {
                return this.inspeedField;
            }
            set {
                this.inspeedField = value;
                this.RaisePropertyChanged("inspeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int outmethod {
            get {
                return this.outmethodField;
            }
            set {
                this.outmethodField = value;
                this.RaisePropertyChanged("outmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int outspeed {
            get {
                return this.outspeedField;
            }
            set {
                this.outspeedField = value;
                this.RaisePropertyChanged("outspeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int stopmethod {
            get {
                return this.stopmethodField;
            }
            set {
                this.stopmethodField = value;
                this.RaisePropertyChanged("stopmethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int stopspeed {
            get {
                return this.stopspeedField;
            }
            set {
                this.stopspeedField = value;
                this.RaisePropertyChanged("stopspeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int stoptime {
            get {
                return this.stoptimeField;
            }
            set {
                this.stoptimeField = value;
                this.RaisePropertyChanged("stoptime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DisplayObj : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int objTypeIndexField;
        
        private TextPro textProField;
        
        private PicturePro pictureProField;
        
        private DateTimePro dateTimeProField;
        
        private ClockPro clockProField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ObjTypeIndex {
            get {
                return this.objTypeIndexField;
            }
            set {
                this.objTypeIndexField = value;
                this.RaisePropertyChanged("ObjTypeIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TextPro TextPro {
            get {
                return this.textProField;
            }
            set {
                this.textProField = value;
                this.RaisePropertyChanged("TextPro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PicturePro PicturePro {
            get {
                return this.pictureProField;
            }
            set {
                this.pictureProField = value;
                this.RaisePropertyChanged("PicturePro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DateTimePro DateTimePro {
            get {
                return this.dateTimeProField;
            }
            set {
                this.dateTimeProField = value;
                this.RaisePropertyChanged("DateTimePro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ClockPro ClockPro {
            get {
                return this.clockProField;
            }
            set {
                this.clockProField = value;
                this.RaisePropertyChanged("ClockPro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ELDRegion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int region_IndexField;
        
        private string eLD_IPField;
        
        private int road_idField;
        
        private int regionTypeField;
        
        private int topField;
        
        private int leftField;
        
        private int widthField;
        
        private int heightField;
        
        private int borderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Region_Index {
            get {
                return this.region_IndexField;
            }
            set {
                this.region_IndexField = value;
                this.RaisePropertyChanged("Region_Index");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ELD_IP {
            get {
                return this.eLD_IPField;
            }
            set {
                this.eLD_IPField = value;
                this.RaisePropertyChanged("ELD_IP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int road_id {
            get {
                return this.road_idField;
            }
            set {
                this.road_idField = value;
                this.RaisePropertyChanged("road_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int RegionType {
            get {
                return this.regionTypeField;
            }
            set {
                this.regionTypeField = value;
                this.RaisePropertyChanged("RegionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
                this.RaisePropertyChanged("top");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
                this.RaisePropertyChanged("left");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
                this.RaisePropertyChanged("border");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] fileBytes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fileName;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(byte[] fileBytes, string fileName) {
            this.fileBytes = fileBytes;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UploadFileResult;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(string UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileII", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileIIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] fileBytes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string path;
        
        public UploadFileIIRequest() {
        }
        
        public UploadFileIIRequest(byte[] fileBytes, string fileName, string path) {
            this.fileBytes = fileBytes;
            this.fileName = fileName;
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileIIResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileIIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UploadFileIIResult;
        
        public UploadFileIIResponse() {
        }
        
        public UploadFileIIResponse(string UploadFileIIResult) {
            this.UploadFileIIResult = UploadFileIIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ELDWebServiceSoapChannel : ClientDemo.hh.ELDWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ELDWebServiceSoapClient : System.ServiceModel.ClientBase<ClientDemo.hh.ELDWebServiceSoap>, ClientDemo.hh.ELDWebServiceSoap {
        
        public ELDWebServiceSoapClient() {
        }
        
        public ELDWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ELDWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ELDWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ELDWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPath(string path) {
            return base.Channel.GetPath(path);
        }
        
        public System.Threading.Tasks.Task<string> GetPathAsync(string path) {
            return base.Channel.GetPathAsync(path);
        }
        
        public string FenPingII(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.ELDRegion[] arrEldRegion) {
            return base.Channel.FenPingII(myTDeviceParam, arrEldRegion);
        }
        
        public System.Threading.Tasks.Task<string> FenPingIIAsync(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.ELDRegion[] arrEldRegion) {
            return base.Channel.FenPingIIAsync(myTDeviceParam, arrEldRegion);
        }
        
        public string AddGaoJingXinXiToDb(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.DisplayObj displayObj, int RegionIndex) {
            return base.Channel.AddGaoJingXinXiToDb(myTDeviceParam, displayObj, RegionIndex);
        }
        
        public System.Threading.Tasks.Task<string> AddGaoJingXinXiToDbAsync(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.DisplayObj displayObj, int RegionIndex) {
            return base.Channel.AddGaoJingXinXiToDbAsync(myTDeviceParam, displayObj, RegionIndex);
        }
        
        public string SendObjToELD(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.DisplayObj displayObj, int RegionIndex) {
            return base.Channel.SendObjToELD(myTDeviceParam, displayObj, RegionIndex);
        }
        
        public System.Threading.Tasks.Task<string> SendObjToELDAsync(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.DisplayObj displayObj, int RegionIndex) {
            return base.Channel.SendObjToELDAsync(myTDeviceParam, displayObj, RegionIndex);
        }
        
        public string SendArrToELD(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.ELDRegion region, ClientDemo.hh.DisplayObj[] arrdisplayObj) {
            return base.Channel.SendArrToELD(myTDeviceParam, region, arrdisplayObj);
        }
        
        public System.Threading.Tasks.Task<string> SendArrToELDAsync(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.ELDRegion region, ClientDemo.hh.DisplayObj[] arrdisplayObj) {
            return base.Channel.SendArrToELDAsync(myTDeviceParam, region, arrdisplayObj);
        }
        
        public string SendToELD(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.ELDRegion region, ClientDemo.hh.DisplayObj displayObj) {
            return base.Channel.SendToELD(myTDeviceParam, region, displayObj);
        }
        
        public System.Threading.Tasks.Task<string> SendToELDAsync(ClientDemo.hh.MyTDeviceParam myTDeviceParam, ClientDemo.hh.ELDRegion region, ClientDemo.hh.DisplayObj displayObj) {
            return base.Channel.SendToELDAsync(myTDeviceParam, region, displayObj);
        }
        
        public string AdjustTime(ClientDemo.hh.MyTDeviceParam myTDeviceParam) {
            return base.Channel.AdjustTime(myTDeviceParam);
        }
        
        public System.Threading.Tasks.Task<string> AdjustTimeAsync(ClientDemo.hh.MyTDeviceParam myTDeviceParam) {
            return base.Channel.AdjustTimeAsync(myTDeviceParam);
        }
        
        public string SetSwitch(int val) {
            return base.Channel.SetSwitch(val);
        }
        
        public System.Threading.Tasks.Task<string> SetSwitchAsync(int val) {
            return base.Channel.SetSwitchAsync(val);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientDemo.hh.UploadFileResponse ClientDemo.hh.ELDWebServiceSoap.UploadFile(ClientDemo.hh.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public string UploadFile(byte[] fileBytes, string fileName) {
            ClientDemo.hh.UploadFileRequest inValue = new ClientDemo.hh.UploadFileRequest();
            inValue.fileBytes = fileBytes;
            inValue.fileName = fileName;
            ClientDemo.hh.UploadFileResponse retVal = ((ClientDemo.hh.ELDWebServiceSoap)(this)).UploadFile(inValue);
            return retVal.UploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientDemo.hh.UploadFileResponse> ClientDemo.hh.ELDWebServiceSoap.UploadFileAsync(ClientDemo.hh.UploadFileRequest request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientDemo.hh.UploadFileResponse> UploadFileAsync(byte[] fileBytes, string fileName) {
            ClientDemo.hh.UploadFileRequest inValue = new ClientDemo.hh.UploadFileRequest();
            inValue.fileBytes = fileBytes;
            inValue.fileName = fileName;
            return ((ClientDemo.hh.ELDWebServiceSoap)(this)).UploadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientDemo.hh.UploadFileIIResponse ClientDemo.hh.ELDWebServiceSoap.UploadFileII(ClientDemo.hh.UploadFileIIRequest request) {
            return base.Channel.UploadFileII(request);
        }
        
        public string UploadFileII(byte[] fileBytes, string fileName, string path) {
            ClientDemo.hh.UploadFileIIRequest inValue = new ClientDemo.hh.UploadFileIIRequest();
            inValue.fileBytes = fileBytes;
            inValue.fileName = fileName;
            inValue.path = path;
            ClientDemo.hh.UploadFileIIResponse retVal = ((ClientDemo.hh.ELDWebServiceSoap)(this)).UploadFileII(inValue);
            return retVal.UploadFileIIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientDemo.hh.UploadFileIIResponse> ClientDemo.hh.ELDWebServiceSoap.UploadFileIIAsync(ClientDemo.hh.UploadFileIIRequest request) {
            return base.Channel.UploadFileIIAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientDemo.hh.UploadFileIIResponse> UploadFileIIAsync(byte[] fileBytes, string fileName, string path) {
            ClientDemo.hh.UploadFileIIRequest inValue = new ClientDemo.hh.UploadFileIIRequest();
            inValue.fileBytes = fileBytes;
            inValue.fileName = fileName;
            inValue.path = path;
            return ((ClientDemo.hh.ELDWebServiceSoap)(this)).UploadFileIIAsync(inValue);
        }
        
        public string SendWords(string words) {
            return base.Channel.SendWords(words);
        }
        
        public System.Threading.Tasks.Task<string> SendWordsAsync(string words) {
            return base.Channel.SendWordsAsync(words);
        }
        
        public string GetMessage() {
            return base.Channel.GetMessage();
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync() {
            return base.Channel.GetMessageAsync();
        }
        
        public ClientDemo.hh.TextObj GetTextObj(string eldIp) {
            return base.Channel.GetTextObj(eldIp);
        }
        
        public System.Threading.Tasks.Task<ClientDemo.hh.TextObj> GetTextObjAsync(string eldIp) {
            return base.Channel.GetTextObjAsync(eldIp);
        }
        
        public ClientDemo.hh.road[] GetRoadsByDisplayType(int displayType) {
            return base.Channel.GetRoadsByDisplayType(displayType);
        }
        
        public System.Threading.Tasks.Task<ClientDemo.hh.road[]> GetRoadsByDisplayTypeAsync(int displayType) {
            return base.Channel.GetRoadsByDisplayTypeAsync(displayType);
        }
        
        public ClientDemo.hh.region[] Search(string eldIp) {
            return base.Channel.Search(eldIp);
        }
        
        public System.Threading.Tasks.Task<ClientDemo.hh.region[]> SearchAsync(string eldIp) {
            return base.Channel.SearchAsync(eldIp);
        }
    }
}
